spring:
    datasource:
        url: jdbc:h2:mem:learndb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_ADDRESS}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
server:
    port: 8080
